In [19]:
##a
import numpy as np

# Step a: Create random vector of size 15 with integers from 1 to 20
arr = np.random.randint(1, 21, size=15)
print("Original array:", arr)

# 1. Reshape the array to 3 by 5
arr = arr.reshape(3, 5)
print("\nReshaped array (3x5):\n", arr)

# 2. Print array shape
print("\nShape of array:", arr.shape)

# 3. Replace the max in each row by 0
for i in range(arr.shape[0]):
    max_index = np.argmax(arr[i])  # Find index of max value in row i
    arr[i, max_index] = 0          # Replace max with 0

print("\nArray after replacing max in each row by 0:\n", arr)


Original array: [10 12  1  3 15  6 11  3  3 14 18  1 15  9 10]

Reshaped array (3x5):
 [[10 12  1  3 15]
 [ 6 11  3  3 14]
 [18  1 15  9 10]]

Shape of array: (3, 5)

Array after replacing max in each row by 0:
 [[10 12  1  3  0]
 [ 6 11  3  3  0]
 [ 0  1 15  9 10]]


In [20]:
##b
import numpy as np

# Create a 4x3 array with 4-byte (32-bit) integer elements
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

# Print the array
print("Array:\n", arr)

# Print shape, type, and data type
print("\nShape of array:", arr.shape)
print("Type of array:", type(arr))
print("Data type of elements:", arr.dtype)



Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape of array: (4, 3)
Type of array: <class 'numpy.ndarray'>
Data type of elements: int32


In [21]:
##c
import numpy as np

# Define the square array
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print results
print("Eigenvalues:", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [22]:
##d
import numpy as np

# Define the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Get the diagonal elements
diagonal_elements = np.diagonal(arr)

# Compute the sum of the diagonal elements
sum_diagonal = diagonal_elements.sum()

# Print results
print("Diagonal elements:", diagonal_elements)
print("Sum of diagonal elements:", sum_diagonal)


Diagonal elements: [0 4]
Sum of diagonal elements: 4


In [23]:
##e
import numpy as np

# Create original 3x2 array
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

# Reshape to 2x3
new_arr = arr.reshape(2, 3)

# Print the reshaped array
print(new_arr)


[[1 2 3]
 [4 5 6]]


Video Link: https://drive.google.com/file/d/1keAjT9SmHOOv0VgAseZUz1WTSY84THEn/view?usp=sharing